domain_path: E:\project\vivado\Zynq\test_accelarator\vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
